name: Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Changelog
      uses: actions/npm@v2
      with:
        command: run
        args: conventional-changelog

    - name: Commit Changelog
      uses: endbugs/actions-create-or-update-file@v2
      with:
        file-path: CHANGELOG.md
        file-content: ${{ steps.generate_changelog.outputs.stdout }}
        commit-message: "chore(changelog): Generate Changelog [skip ci]"
