name: Release Workflow

on:
  push:
    branches:
      - 'release/*'
  create:
    type: branch
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create or update Todo List
        uses: EndBug/add-and-commit@v9
        with:
          file-name: TODO-LIST.md
          file-content: |
            # Todo List

            $(grep -r --exclude-dir=vendor --exclude=*.md 'TODO' . | sed -e 's/^/  * /')

      - name: Create or update Changelog
        uses: EndBug/add-and-commit@v9
        with:
          file-name: CHANGELOG.md
          file-content: |
            # Changelog

            $(conventional-changelog -p angular)

      - name: Create or update Issue List
        uses: EndBug/add-and-commit@v9
        with:
          file-name: ISSUE-LIST.md
          file-content: |
            # Issue List

            $(curl -H "Authorization: token $(GITHUB_TOKEN)" https://api.github.com/repos/$GITHUB_REPOSITORY/issues | jq '.[].title' -r | sed -e 's/^/  * /')

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          commit: true
          push: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
