name: Release Workflow

on:
  push:
    branches:
      - 'release/*'
  create:
    type: branch
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create or update Todo List
        run: |
          TODO_LIST=$(grep -r --exclude-dir=vendor --exclude=*.md 'TODO' . | sed -e 's/^/  * /')
          echo "$TODO_LIST" > TODO-LIST.md

      - name: Install conventional-changelog
        run: |
          npm install -g conventional-changelog

      - name: Create or update Changelog
        run: |
          CHANGELOG=$(conventional-changelog -p angular)
          echo "$CHANGELOG" > CHANGELOG.md

      - name: Create or update Issue List
        run: |
          ISSUE_LIST=$(curl -H "Authorization: token $(GITHUB_TOKEN)" https://api.github.com/repos/$GITHUB_REPOSITORY/issues | jq '.[].title' -r | sed -e 's/^/  * /')
          echo "$ISSUE_LIST" > ISSUE-LIST.md

      - name: Add and Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "Amadon"
          author_email: "amadon83@gmail.com"
          message: "Commit from GitHub Actions (Release Workflow)"
          add: "['TODO-LIST.md','CHANGELOG.md','ISSUE-LIST.md']"
